### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by chenzhekl** [tlycken/Contour.jl#17]
I ran `Pkg.update()`, and this is what I got. 

    julia> Pkg.update()
    INFO: Updating METADATA...
    INFO: Computing changes...
    INFO: Upgrading ArrayViews: v0.4.6 => v0.4.8
    INFO: Installing Calculus v0.1.5
    INFO: Upgrading Codecs: v0.1.2 => v0.1.3
    INFO: Upgrading Color: v0.3.8 => v0.3.15
    INFO: Installing Compat v0.2.10
    INFO: Upgrading Compose: v0.3.9 => v0.3.10
    INFO: Upgrading Contour: v0.0.4 => v0.0.6
    INFO: Rolling back Compose from v0.3.10 to v0.3.9
    INFO: Rolling back install of Compat
    INFO: Rolling back Color from v0.3.15 to v0.3.8
    INFO: Rolling back Codecs from v0.1.3 to v0.1.2
    INFO: Rolling back install of Calculus
    INFO: Rolling back ArrayViews from v0.4.8 to v0.4.6
    ERROR: Contour: fetch failed to get commit 7bded64ef5, please file an issue at https://github.com/tlycken/Contour.jl/issues
     in error at error.jl:21
     in fetch at pkg/write.jl:19
     in update at pkg/write.jl:41
     in resolve at /opt/homebrew-cask/Caskroom/julia/0.3.5/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
     in update at /opt/homebrew-cask/Caskroom/julia/0.3.5/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
     in anonymous at pkg/dir.jl:28
     in cd at /opt/homebrew-cask/Caskroom/julia/0.3.5/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
     in __cd#227__ at /opt/homebrew-cask/Caskroom/julia/0.3.5/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib
     in update at /opt/homebrew-cask/Caskroom/julia/0.3.5/Julia-0.3.5.app/Contents/Resources/julia/lib/julia/sys.dylib

**Comment by tlycken** [comment]
Thanks for the report!

However, I'm not able to reproduce it; I've tried both Julia 0.3.4 and 0.3.5, and both installing Contour from scratch as well as updating specifically from 0.0.4 to 0.0.6 (which is what you tried), all without error.

Could it simply be a network error, or something similar? What happens if you try `Pkg.update()` again?

**Comment by chenzhekl** [comment]
The same error happens every time I try `Pkg.update()`. 

I guess it may have something to do with the way I installed julia.

    brew install caskroom/cask/brew-cask
    brew update
    brew cask install julia

**Comment by tlycken** [comment]
Hm. I don't see anything immediately problematic with that, but I'm not a mac user so I can't know for sure. Also, I don't have a mac to try this out on, so it's going to be difficult for me to help single-handedly. You might want to post to the [julia-users forum](https://groups.google.com/forum/#!forum/julia-users) and see if there's anyone there who can help you track down the root cause of the error. Be sure to link to this issue, and post here again if there's anything I can/need to do to fix the problem.

Thanks a lot!

**Comment by tlycken** [comment]
By the way, have you tried deleting your entire `~/.julia` directory? That can usually solve a lot of issues with corrupt package installations, so if this is indeed a corruption problem, that should fix it for you.

**Comment by chenzhekl** [comment]
Thanks! Deleting the entire `~/.julia` directory did work.
